# Generated by Django 5.1.3 on 2024-11-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=40),
        ),
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.CharField(default='48999999999', max_length=20),
        ),
    ]
