# Generated by Django 5.1.3 on 2024-11-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers_email_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, default='default@example.com', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank=True, default='48999999999', max_length=20, null=True),
        ),
    ]
