# Generated by Django 5.1.3 on 2024-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customers_email_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
