# Generated by Django 5.1.3 on 2024-11-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customers_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
