# Generated by Django 5.1.1 on 2024-11-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=3)),
                ('local', models.CharField(max_length=25)),
                ('p_cost', models.FloatField()),
                ('p_sell', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
    ]
