# Generated by Django 5.1.3 on 2024-11-16 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.units'),
        ),
    ]
